name: Scheduled Auto Cite by Crawler

on:
  schedule:
    - cron: '00 9 * * *' 

jobs:
  update_research:
    name: Auto Cite by Crawler
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install packages
        run: python -m pip install --upgrade --requirement ./auto-cite/requirements.txt
      - name: Installed package list
        run: apt list --installed
      # - name: Remove Chrome
      #   run: sudo apt purge google-chrome-stable
      # - name: Remove default Chromium
      #   run: sudo apt purge chromium-browser
      # - name: Install a new Chromium
      #   run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Build updated citations
        run: python ./auto-cite/auto-cite-by-crawler.py
        timeout-minutes: 60
      - name: Create and checkout new branch
        run: |
          git checkout -b auto-cite-by-crawler
      - name: Commit and push
        run: |
          git config --local user.email "qian.dong.97@qq.com"
          git config --local user.name "Qian Dong"
          git add .
          git commit -m "Auto Cite by Crawler"
          git push origin auto-cite-by-crawler
      - name: Merge branch into main
        run: |
          git checkout main
          git merge auto-cite-by-crawler --no-edit --no-ff
          git push -f origin main
      - name: Delete branch
        run: |
          git push origin --delete auto-cite-by-crawler
