name: Scheduled Auto Cite by Crawler

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update_research:
    name: Auto Cite by Crawler
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
      
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: 3.9
      
      - name: Install packages
        run: python -m pip install --upgrade --requirement ./auto-cite/requirements.txt
      
      - name: Install Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '16'
      
      - name: Install Chrome using Puppeteer
        run: npx @puppeteer/browsers install chrome@128.0.6613.113
      
      - name: Install ChromeDriver using Puppeteer
        run: npx @puppeteer/browsers install chromedriver@128.0.6613.113
      
      - name: Set environment variables for browser paths
        run: |
          # Find Chrome binary and set path
          CHROME_BIN=$(find . -name "chrome" | grep -E "chrome-linux.*\/chrome$" | head -n 1)
          echo "CHROME_PATH=$(readlink -f $CHROME_BIN)" >> $GITHUB_ENV
          
          # Find ChromeDriver binary and set path
          CHROMEDRIVER_BIN=$(find . -name "chromedriver" | grep -E "chromedriver-linux.*\/chromedriver$" | head -n 1)
          echo "CHROMEDRIVER_PATH=$(readlink -f $CHROMEDRIVER_BIN)" >> $GITHUB_ENV
          
          # Print paths for debugging
          echo "Chrome binary path: $(readlink -f $CHROME_BIN)"
          echo "ChromeDriver path: $(readlink -f $CHROMEDRIVER_BIN)"
      
      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      
      - name: Build updated citations
        run: python ./auto-cite/auto-cite-by-crawler.py
        env:
          CHROME_BINARY_PATH: ${{ env.CHROME_PATH }}
          CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
          PYTHONUNBUFFERED: "1"
        timeout-minutes: 55  # Gives some buffer before the job timeout
      
      - name: Commit updated citations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_data/citations.yaml"
          commit_message: "Generate citations by daily scheduled crawler"
          push_options: --force
